export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';
export const SET_MOVIE_DETAILS_LOADER = 'SET_MOVIE_DETAILS_LOADER';
export const SET_MOVIE_DETAILS_ERROR = 'SET_MOVIE_DETAILS_ERROR';