export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const SET_TRENDING_MOVIES = 'SET_TRENDING_MOVIES';
export const SET_PAGE_TOTAL = 'SET_PAGE_TOTAL';
export const SET_ACTIVE_PAGE='SET_ACTIVE_PAGE';
export const SEARCH_TRENDING_MOVIES = 'SEARCH_TRENDING_MOVIES';
export const SET_TRENDING_MOVIES_LOADER = 'SET_TRENDING_MOVIES_LOADER';
export const SET_TRENDING_MOVIES_ERROR = 'SET_TRENDING_MOVIES_ERROR';